### ISSUE TITLE
unable to find rev11-10 in commits

### ISSUE THREAD

**Issue by classilla** [sttz/MPlayer-OSX-Extended#100]
There doesn't seem to be a tag or release corresponding with any version of rev11. https://github.com/sttz/MPlayer-OSX-Extended/commits/f7f1abc4a2a9d8dc5199575cc7d51d446e5f8e77 appears to be the first rev12, but the bundle version jumps from 1104 to 1201, implying that the 1110 in the final release of rev11 came from some other branch. Where is this stored?

Alternatively, what was landed on that branch (and I can try to reconstruct it locally)?

Thanks!

**Comment by sttz** [comment]
Seems like I missed to commit the version bump of rev11.

Given that rev11 was released on 27th June 2009, 538990ab8bf78d7c72f934197df5a367dad72004 should be the corresponding commit.

The next commit is only on 2nd October, so the above commit should contain everything that went into rev11, except the version bump in Info.plist.

**Comment by classilla** [comment]
Thank you very much!
