### ISSUE TITLE
scrubbing bar does not show on .m2ts files

### ISSUE THREAD

**Issue by nushi91** [sttz/MPlayer-OSX-Extended#106]
.m2ts files when opened on mplay dont show the scrubbing bar. infact i cant even forward the video unless i got to playback > seek> time. is there a solution for it? thanks!

**Comment by ballo** [comment]
I had the same problem with a 1080p mkv x264, but it came back after I went fullscreen then back to windowed. Did you try this?

**Comment by nushi91** [comment]
it didnt work. it shows up like this: https://imgur.com/unRttqZ
