### ISSUE TITLE
Screenshot not capturing whole screen

### ISSUE THREAD

**Issue by JavascriptCockup** [sttz/MPlayer-OSX-Extended#109]
I've got several Mpeg TS files from PAL DVB-T broadcasts that swap between 16:9 and 4:3 throughout the file. MPlayer alters the window size accordingly as it plays the file.

MediaInfo reports the files as being 544 wide x 576 high, I'm guessing this image must be stretched horizontally by the player when it sees the 4:3 and 16:9 flags during playback?

However if I do a screengrab, the screengrab doesn't capture the whole image, it just captures a 544 x 576 section of the image, so for a 16:9 capture it's pretty much just the left hand half of the picture.

Is there a way to solve this so Mplayer screengrabs the whole picture that I am viewing?

**Comment by sttz** [comment]
This issue needs to be raised with MPlayer, which takes care of capturing the screenshots. MPE only instructs MPlayer to do so. (.e.g. on [mplayer-users](http://lists.mplayerhq.hu/mailman/listinfo/mplayer-users).)

However, there hasn't been much activity on MPlayer and most developers seem to have moved on to [mpv](https://mpv.io). I suggest you try with mpv or [IINA](https://iina.io) (if you prefer a nicer frontend) and then report an issue with mpv if you have the same problem.
