### ISSUE TITLE
Customize seek time / input.conf issue

### ISSUE THREAD

**Issue by tobia** [sttz/MPlayer-OSX-Extended#23]
Hi

I'm trying to change the left / right arrow seek time, because 10 seconds is too much when you've just missed the last word of a subtitle.

I've tried setting `~/.mplayer/input.conf` as suggested online:

```
RIGHT seek 1
LEFT seek -1
```

If I call the mplayer binary from the commandline it works, but Mplayer OSX Extended won't pick it up.
I added -v to the advanced options and looked at the logs: it seems it's trying to open `/usr/local/etc/mplayer/input.conf`
But even adding that, and seeing `input.conf parsed: 2 binds` in the logs, it still won't work.

So it seems Mplayer OSX Extended has its own bindings, independent from mplayer's ones.

That's well and good, but can we please have a setting for the seek time? Even a single multiplier to apply to all six seek times would be great.

**Comment by kocoman1** [comment]
link above doesn't work anymore

**Comment by sttz** [comment]
@kocoman1 The page is included in MPE's help. Open it with ⌘? and then select «Advance Options».
