### ISSUE TITLE
AppleScript support

### ISSUE THREAD

**Issue by TD912** [sttz/MPlayer-OSX-Extended#30]
Applescript support would be a great addition to MPlayer OSX Extended, although it might take a bit of work to implement.

There's some basic documentation on the Apple dev site: https://developer.apple.com/library/mac/samplecode/SimpleScripting/Introduction/Intro.html

Besides being able to control media playback, it would be nice to be able to script it to open URLs or add things to the playlist. It would also be nice to be able to read properties of the media being played, like bitrate, video/audio format, duration, resolution, etc. Similar to how QuickTime Player and VLC is able to be scripted.

**Comment by RuolunWeng** [comment]
Dear Developers,

Did someone solve this question?


Allen
