### ISSUE TITLE
Jubler with .mov images

### ISSUE THREAD

**Issue by 3aSZ** [sttz/MPlayer-OSX-Extended#57]
I'm using Jubler as a subtitling tool. When I try to see a movie .mov format the sound go veeeery slow, so I can't not use it at all.
Somebody told me that it was probably some sort of trouble with MPlayer
I can only use the "Try subtitles from current position" key to see the images and hear the sound at a normal speed.
Can I only watch imatges on .jpg format?
What can I do to be able to work with images with .mov format?

Thank you

**Comment by sttz** [comment]
This is the repository for MPE, a GUI frontend for MPlayer for OS X. We can't help you with issues regarding another project.
