### ISSUE TITLE
Out of sync with rev15 - Had to revert to rev 14

### ISSUE THREAD

**Issue by pounia** [sttz/MPlayer-OSX-Extended#60]
After rev15 update, sound was out of sync on all videos by about 200ms
Had to trash it, reloaded rev 14 --> It's back to normal.

I use a 2011 Macbookpro   2 GHz Intel Core / OS X 10.9.2

Cheers

**Comment by sttz** [comment]
Can you try with rev16-test1?

If the problem still occurs, it would be great if you could find a freely available video file that exhibits the problem so that I can try to reproduce it.
