### ISSUE TITLE
Time counter doesn't count

### ISSUE THREAD

**Issue by TheButterZone** [sttz/MPlayer-OSX-Extended#62]
It just displays the runtime of the entire video statically.

Rev 15 1511

**Comment by sttz** [comment]
Did you try clicking on the time?

It cycles through played time > remaining time > video length. You can also cycle through them using the tab key.

**Comment by TheButterZone** [comment]
Ok, that worked. Should I start a separate issue for the progress indicator dot not moving across the timeline?

**Comment by sttz** [comment]
It gets displayed but doesn't move?

Just to make sure, can you check if the problem is still present in rev16-test1?

**Comment by TheButterZone** [comment]
No dot, just white line. I guess it's called the scrubbing bar, per the release notes. The dock icon is in  seemingly endless loading dot flashing loop now.
