### ISSUE TITLE
MPlayer rev15 (1511) does not allow me to use video equalizer

### ISSUE THREAD

**Issue by ViSuaLMoG** [sttz/MPlayer-OSX-Extended#63]
no issues opening and playing video files. but when I attempt to enable the video equalizer, (to adjust the brightness) the video stops playing and will no longer play. i have to disable the equalizer for video playback to function normally again. this is affecting any multiple videos i attempted to test, most of them .avi files

**Comment by sttz** [comment]
Likely fixed in 3387b7d.
