### ISSUE TITLE
MPlayer initially doesn't open with videos aspect

### ISSUE THREAD

**Issue by wtraxinger** [sttz/MPlayer-OSX-Extended#64]
I'm running MPlayer rev 15 (r36986) on a Macboox Pro (Mavericks).
When starting up MPlayer via double-clicking on a video file, the window does not open using the videos aspect ratio, instead opens the window in a square window, showing black bars on top and bottom.
When MPlayer is already running, starting any video again the same way by double clicking, the window size is adjusted correctly to the videos aspect ratio without black bars.
The correct behaviour was implemented in rev 14.

Any chance to fix this?
Thanks

**Comment by sttz** [comment]
Fixed in rev16-test2
