### ISSUE TITLE
doesn't auto load external subtitles with movie.eng.srt

### ISSUE THREAD

**Issue by mik385** [sttz/MPlayer-OSX-Extended#65]
i am using rev15, it doesn't load srt with "eng" in front of the .srt... it can only works with movie.srt

i am using movie.eng.srt as i have multiple srt in a folder.

any advise?

**Comment by M0rtenB** [comment]
I have the same problem. It would be nice if subtitles with extended names (such as Subliminal produces and Plex requires) were recognized.

**Comment by sttz** [comment]
MPE is currently relying on MPlayer to load the external subtitles. You can use the `-sub-fuzziness` option to make it load more subtitles:

     -sub-fuzziness <mode>
         Adjust matching fuzziness when searching for subtitles:
            0    exact match (default)
            1    Load all subs containing movie name.
            2    Load all subs in the current and -sub-paths directories.

Add `-sub-fuzziness 1` to the Additional Options in the Advanced section in MPE's Preferences to load all subtitles that contain the current movie's name.
