### ISSUE TITLE
Playback Speed & Playlists

### ISSUE THREAD

**Issue by nayrnet** [sttz/MPlayer-OSX-Extended#67]
Mplayer OSX Extended is the only OSX Video player I have found that plays h264 video files from my security cameras (*.dav files).

If I add a bunch of recording clips (10m segments) to a playlist and set it to play through it automatically I have to reset Playback Speed settings for each file.. Since I may be trying to find an event in a several hour window I need to review the files with a high playback speed.

It would be great if the Playback Settings in the inspector window would not reset upon the next file in a playlist.

**Comment by sttz** [comment]
All settings in the inspector are on a per-file basis. I don't think I will make them global but you should be able to multi-edit them.

In the meantime, you can globally set the playback speed in Preferences under Advanced by adding and enabling a new option with "-speed x.x", where x.x is the speed factor you want to use. This doesn't play too nice with the setting in the inspector, so you should use one or the other at a time.
