### ISSUE TITLE
Mouse pointer disappears after leaving fullscreen mode in Yosemite

### ISSUE THREAD

**Issue by 4chanmoot** [sttz/MPlayer-OSX-Extended#71]
On Yosemite, when you watch a video fullscreen, perform a back or forward skip, and then leave fullscreen, the mouse pointer disappears. This didn't happen until installing Yosemite.

To Reproduce:
1. Open a video
2. Press F to enter fullscreen mode
3. Press right arrow to skip ahead in the video
4. Press F to exit fullscreen mode

Expected: Mouse pointer appears
Actual: Mouse pointer is invisible until you switch out of the app

Tested with rev15 on an MBP 2011 with OS 10.10.0

**Comment by 4chanmoot** [comment]
Is this project still alive?

**Comment by sttz** [comment]
Should be fixed in abbd1e4.
