### ISSUE TITLE
Just doesn't work anymore!

### ISSUE THREAD

**Issue by z00m3rr** [sttz/MPlayer-OSX-Extended#72]
I admit I've got an older Mac with some possible OS and/or hardware issues, but I can't see why the damn thing would stop working altogether.

Have been using the Player for several years; tried upgrading to rev15 around Feb 2014 but it didn't seem to work -- just opened a windowless player, took some time to load the movie but never opened a window to start playing. Reverted to rev14 and it worked fine until this week. I've tried playing some older movies that I know used to play fine, but same result -- nada.

Tried installing the update rev15 (I understand there was an issue with the first build) -- nothing. Installed the Essential Codes Package for good measure -- zilch. WTF is going on??

iMac 2009 3GHz, 4GB RAM, Mac OS X 10.8.5

**Comment by z00m3rr** [comment]
Clean install of Mac OS X Yosemite last weekend; MPlayer-OSX-Extended still doesn't work. :(

**Comment by christopheranderton** [comment]
While this is an old thread, i do not have the same problems on 10.10.4 (iMac 27" Early 2011).

**Comment by asoksevil** [comment]
Use mpv.

**Comment by sttz** [comment]
Please try with rev16-test1 and report back if it still doesn't work.

**Comment by christopheranderton** [comment]
Sorry for posting in a closed thread. I'm pleased that the new version (rev16-test1) **works flawlessly** on OS X 10.11.1 on my system. 

Feels snappier also (mostly use MPV, but this one is a work horse). And congrats on the game. Looks great. Love the in game artwork and the soundtrack!

**Comment by z00m3rr** [comment]
Hi, gang;

Sorry I didn't keep up with this thread; a thousand other things! :D I'll
keep these suggestions in mind, thanks. I'm not feeling ready for El
Capitan yet; got a 6-yr-old iMac that doesn't get along with Mavericks or
Yosemite that well yet.

Yes, I'm one of those obsessive evaluation/tinkering freaks who has
multiple boot volumes, internal and external, with at least three distinct
OS X versions in play. I guess it's a hobby... well, I suppose I could try
El Capitan...

// RR
