### ISSUE TITLE
Playback progress cursor does not appear in OS X El Capitan

### ISSUE THREAD

**Issue by newacct** [sttz/MPlayer-OSX-Extended#75]
In OS X El Capitan (10.11), the thing that shows you the progress of where you are in the duration of the video does not show up anymore.

**Comment by Heiki-kun** [comment]
Not only that, but playback seems to be broken as well. I can`t explain it, but it looks like the video suffers from interlacing issues.

**Comment by biziclop** [comment]
It's not interlacing, it's simply resizing video frames using nearest neighbour instead of whatever it used.
I wonder if manually updating the mplayer binaries / arguments could fix it, see here:
`MPlayer OSX Extended.app/Contents/Resources/Binaries/mpextended.mpBinaries/Contents`

**Comment by CyberStrike** [comment]
:+1:

**Comment by sttz** [comment]
Should be fixed in c11dedf and a2976e8.
