### ISSUE TITLE
The project is dead everybody.

### ISSUE THREAD

**Issue by negativeions** [sttz/MPlayer-OSX-Extended#77]
When is the next version going to be released? A pre-release maybe? There isn't a single good video player for OSX. Every single one has major issues. Meanwhile windows has MPC-HC and it's amazing. OSX will never have anything that good and it makes me sick. No way in hell I'm using windows again.

**Comment by asoksevil** [comment]
Mpv

**Comment by biziclop** [comment]
Apparently, it isn't!
See the commits: https://github.com/sttz/MPlayer-OSX-Extended/commits/master
Thank you Adrian very much!
But where is the Donate button? :)

**Comment by sttz** [comment]
rev16-test1 is out: https://github.com/sttz/MPlayer-OSX-Extended/releases/tag/rev16-test1

Thanks for the patience!
