### ISSUE TITLE
rev16-test1 rebuilds Fontconfig upon launching first time, no UI indication, hence looks like it hangs

### ISSUE THREAD

**Issue by wimleers** [sttz/MPlayer-OSX-Extended#79]
Crash report attached, let me know what other information you need.

OS X 10.10.5. Early 2009 MacBook Pro 17".
[crash.txt](https://github.com/sttz/MPlayer-OSX-Extended/files/53266/crash.txt)

**Comment by sttz** [comment]
Thanks for the report!

Looking at the report, it was hanging in Fontconfig, though I can't make out what exactly the library was doing at the time.

With the new Fontconfig version the dialog that shows Fontconfig is updating its database isn't working anymore so there's a chance it's just taking its time to do so. Did you try letting it run for a couple of minutes to see if it finishes eventually?

I will fix the dialog in the next beta release.

**Comment by wimleers** [comment]
Now letting it run for a couple of minutes, will report back.

**Comment by wimleers** [comment]
While it runs, note that it _used_ to show a progress bar when it needed to rebuild Fontconfig caches (IIRC that's what it said). So it'd be a (relatively mild) regression to no longer show such a UI indication.

Also note that I specifically say it "hangs upon launch", because the icon keeps bouncing in the dock, which AFAIK indicates the app hasn't fully launched yet. I don't know the internals/details of what causes an app icon to stop bouncing, so I could absolutely be off there.

Just trying to provide as useful feedback as possible :)

**Comment by wimleers** [comment]
And, *yes*, that worked! So it didn't actually hang, it just doesn't show that it's doing its Fontconfig thing. Updating issue title accordingly.

**Comment by TheButterZone** [comment]
This was probably the source of 
https://github.com/sttz/MPlayer-OSX-Extended/issues/80
which returned after today's 10.11.4 update, so I let MPlayer sit awhile and it works again.

**Comment by sttz** [comment]
The dependency on Fontconfig has been removed in rev16-test2, so the hang and the dialog are gone for good!
