### ISSUE TITLE
rev16-test1 destroyed by OSX.11.2 update

### ISSUE THREAD

**Issue by TheButterZone** [sttz/MPlayer-OSX-Extended#80]
Every major video filetype now only plays 1 second worth of audio, green screen or rainbow static video, then requires force quit. MP3s play fine. Videos play fine in Quick Look and MPEG Streamclip.

**Comment by sttz** [comment]
Finally updated to 10.11.2 but could not reproduce your issue.

There is a problem that when the player window resizes at the start of playback you get a green frame with some garbage graphics data but I haven't seen videos being impacted by this.

It would help if you can send me a hang report from when you force quit MPE while it's hanging.

**Comment by TheButterZone** [comment]
Apparently not using MPlayer for 5 days fixed it.
