### ISSUE TITLE
Commandline options not available in Mac OS X

### ISSUE THREAD

**Issue by jdfdj** [sttz/MPlayer-OSX-Extended#82]
Hi there,

I am using mplayer on a Mac Yosemite from commandline to stream video from netcat. However, the following command does not work

``` bash
netcat -l -p 5000 | mplayer -fps 60 -cache 1024 -
```

The output from the commandline is showing an error message from the `open` program. 

```
open: invalid option -- p
Usage: open [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-b <bundle identifier>] [-a <application>] [filenames] [--args arguments]
Help: Open opens files from a shell.
```

I guess that means `mplayer` is calling `open` under the hood, but why doesn't it have its own commandline options anymore? I'm using the version 15.

Thank you.

**Comment by sttz** [comment]
Something is wrong with your setup. MPE doesn't install a `mplayer` binary into your PATH, so that has to come from somewhere else.
