### ISSUE TITLE
MPlayer OSX Extended used by crapware

### ISSUE THREAD

**Issue by christopheranderton** [sttz/MPlayer-OSX-Extended#84]
**UPDATE** 
I wanted to make clear for users coming in here, to know that i nor anyone else is blaming @sttz 
I repeat. This **NOT** the doing of @sttz, he is a victim of bastards using OpenSource software in a illegal manner for their own shady businesses. 

<img width="706" alt="screenshot 2016-11-15 at 18 12 05" src="https://cloud.githubusercontent.com/assets/1305802/20315667/0f00cf10-ab5f-11e6-8746-3c0371846833.png">

---

I stumbled upon this while using the excellent Malwarebytes Anti-Malware scanner for macOS/Mac OS X. First, Malwarebytes has coming down hard on PUPs (Potentially Unwanted Program) as you can read about over here: https://blog.malwarebytes.com/malwarebytes-news/2016/10/malwarebytes-gets-tougher-on-pups/

Now, when doing a scan, i was surprised that i was getting a hit at all (monitoring my system pretty alright in different aspects. *See [1]* ) . To my surprise (lot's of them in this text!) it listed the Mplayer OSX Extended, downloaded and installed from this repo).

<img width="600" alt="1-screen-2016-11-15" src="https://cloud.githubusercontent.com/assets/1305802/20313583/a8497e54-ab57-11e6-93a8-b87be1f07bd8.png">

I tweeted [Thomas Reed](https://twitter.com/thomasareed) (known from The Safe Mac website and now Malwarebytes) from [Malwarebytes](https://blog.malwarebytes.com/) (and included you @sttz ): 
https://twitter.com/Deluxive/status/798203796115439616 (conversation)

I don't know what to do about this. Of course, as i know where my MPlayer OSX Extended is coming from, i can just ignore it. But is not optimal, as users can and will, making the misstake of thinking the legit MPlayer OSX Extended is a ”virus”. 

Now, the crapware installers using a pretty old and modified build, with your @sttz codesigning intact. 

<img width="1549" alt="2-screen-2016-11-15" src="https://cloud.githubusercontent.com/assets/1305802/20313582/a83f6b8a-ab57-11e6-92aa-56a86a9c144a.png">

As a non dev (at least in this area), i don't know what's the proper action to take. Revoke the certificate? I know this project isn't one of your top priorities (understandable!), but i hate to see your name (even if no one is blaming you at all) in Infosec reports. 

## More info

https://www.intego.com/mac-security-blog/silverinstaller-sneakier-than-previously-thought/ (the post also includes the URL to the MPlayer OSX Extended version commonly used by the crapware)

https://www.malwarebytes.com/pup/ (PUP Reconsideration Information)

---

### [1] Tools

*From thrusted sources:* The [Objective-see software](https://objective-see.com/products.html), [Little Flocker](https://www.zdziarski.com/blog/?page_id=6171), [Malwarebytes Anti-Malware](https://www.malwarebytes.com/antimalware/mac/), [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html), hosts file, Firewall (BSD OSS) and some custom written scripts alongside a manual check of the contents of software i'm installing ([Hopper Disassmebler](https://www.hopperapp.com), [Filejuice](http://echoone.com/filejuicer/download) and custom scripts)

**Comment by christopheranderton** [comment]
A late update (very late one!). Thomas Reed from Malwarebytes has removed Mplayer OSX Extended (the @sttz version) from the Malwarebytes Anti-Malware PUP list.

**Comment by sttz** [comment]
Thanks for the research!

Note that I finally released a new beta, you can find it in the GitHub releases.
