### ISSUE TITLE
Progress bar is visible but does not show how much of audio is played

### ISSUE THREAD

**Issue by siamak01** [sttz/MPlayer-OSX-Extended#86]
audio timer indicated correctly.Progress bar is visible but does not show how much of audio is played.
Running OS X 10.12.3

**Comment by cshishaliu** [comment]
I have the same problem.
Is there a solution?

![wx20171011-094240](https://user-images.githubusercontent.com/2427830/31418447-9ef7ae10-ae68-11e7-98f3-6914bf3568a7.png)

**Comment by sttz** [comment]
Try the latest beta, it should fix this issue:
https://github.com/sttz/MPlayer-OSX-Extended/releases/tag/rev16-test2

**Comment by siamak01** [comment]
Great. Thanks. It is working.
