### ISSUE TITLE
Playback slow / Rev11 / Osx 10.4.11

### ISSUE THREAD

**Issue by mrkapqa** [sttz/MPlayer-OSX-Extended#87]
Hello i found that Mplayer OSX Extended is the only Player that plays embedded subtitles on osx Tiger on my Imac G5.
Is there a way to smoothen the playback of the Videos ?

**Comment by sttz** [comment]
In preferences under video there should be an option for fast decoding but I suspect it won't help much.

Unfortunately, OS X 10.4 is no longer supported.
