### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by ghost** [sttz/MPlayer-OSX-Extended#90]
I build it done on macOS High Sierra, and display ok
then I choose a mp4 file, but can't play(click on play button ,nothing changed)
<img width="477" alt="2017-11-15 10 38 58" src="https://user-images.githubusercontent.com/33612080/32815911-3b26e8ac-c9f1-11e7-9ce1-98e267b8634e.png">

**Comment by sttz** [comment]
There's probably something wrong with the mplayer binary. Did you build that yourself or use an existing one?
