### ISSUE TITLE
Rev16 on High Sierra OSD Toggle Key Not Working

### ISSUE THREAD

**Issue by jasonp019** [sttz/MPlayer-OSX-Extended#94]
The OSD toggle key (“o”) is not working to select between OSD display or to turn it off.  This occurs both in full screen as well as windowed mode.

Version is Rev16 on Mac OS High Sierra.

Thank you!

**Comment by sttz** [comment]
What happens when you press the «o» key?

One possibility is that the font you selected couldn't be loaded, try selecting a different font/style.

**Comment by jasonp019** [comment]
I'm not sure what the "«o»" key is.  I am using the key for the lower-case letter "o" and it's not working.  It worked before the upgrade.  The issue is not that the OSD won't display.  It is always on and I can't get it to clear by using the "o" key to toggle through the different options, including where it is no longer displayed.

**Comment by sttz** [comment]
Yeah, I meant the lowercase o key. «» are just fancy quotation marks.

What have you selected in Preferences under Text > On-Screen Display > Show? When you press the o key, does something happen at all? Do you get a beep?
