### ISSUE TITLE
rev16 (1610) on OSX High Sierra forgetting it had been opened previously

### ISSUE THREAD

**Issue by TheButterZone** [sttz/MPlayer-OSX-Extended#95]
![screen shot 2018-02-07 at 12 06 56](https://user-images.githubusercontent.com/2625857/35939036-cc514516-0bff-11e8-9dc6-a7885ea39749.jpg)

**Comment by sttz** [comment]
This is not something in the hands of MPE but macOS. I'm not aware of any way MPE could influence its quarantine and if it could, it would be a security issue.

You can manually remove the quarantine attribute using the command line:

    sudo xattr -rd com.apple.quarantine /Applications/MPlayer\ OSX\ Extended.app

**Comment by TheButterZone** [comment]
I ran that command & it seemed to accept after entering password, but now it's forgotten again after a couple of days. I haven't found another app, not even ones I hadn't used for a long time, to have this issue.
