### ISSUE TITLE
Right click in playlist NOT working!

### ISSUE THREAD

**Issue by siamak01** [sttz/MPlayer-OSX-Extended#96]
I do not recall if this ever was available on older version. But when I try to right click in playlist to delete or any other options nothing comes up. The only way to delete is to choose it from top menu. I am using rev 16(1610)

**Comment by sttz** [comment]
You're right. The playlist is the most outdated aspect of MPE. I've been wanting to update it but haven't had time to do so.

You can use the backspace and delete keys to remove items from the playlist.

**Comment by siamak01** [comment]
it is ok. thanks for all your efforts taking care of MPlayer.
