### ISSUE TITLE
garbage characters for chinese subtitles after new update...

### ISSUE THREAD

**Issue by mik385** [sttz/MPlayer-OSX-Extended#97]
Anyone can advise?

**Comment by cfanpnk** [comment]
I'm having the same issue here

**Comment by sttz** [comment]
Did you try changing the encoding settings in Preferences under Text > Subtitles? Try setting the encoding explicitly or choosing «Chinese» for «Guess Encoding».

Also, if you can share an example subtitle file I can investigate further.

**Comment by qingxiang-jia** [comment]
Not sure if this would help. I encountered the same thing today, choosing a font that supports Chinese works for me, like STHeiti.

**Comment by cfanpnk** [comment]
I changed the font to STHeiti. It did work! Thanks for the tip @qingxiang-jia
