### ISSUE TITLE
-wid option

### ISSUE THREAD

**Issue by navy1978** [sttz/MPlayer-OSX-Extended#98]
Is there a way to pass the Windows id in slave mode, in order to let Player draw on that windows? On windows and linux is working, but on Mac it seems this option is not there...

**Comment by sttz** [comment]
This functionality is not possible on macOS.

MPE uses shared memory to copy the frames from MPlayer to MPE. Look at [MPlayerVideoRenderer.m](https://github.com/sttz/MPlayer-OSX-Extended/blob/master/source/interface/MPlayerVideoRenderer.m) and [vo_corevideo.m](https://github.com/pigoz/mplayer-svn/blob/master/libvo/vo_corevideo.m) in MPlayer to see how this works.

Note that this is pretty outdated. If you're implementing something new, I would take a look at how things are done in MPV as well.

**Comment by navy1978** [comment]
thank you for your reply, is there a way to accomplish that in Java in your opinion?

**Comment by sttz** [comment]
Not with pure Java, I'm afraid. You'd have to write at least some native code and hook it up with the Java side.
